// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: moviedb_service.proto

package moviedb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastAndCrewType int32

const (
	CastAndCrewType_ACTOR              CastAndCrewType = 0
	CastAndCrewType_DIRECTOR           CastAndCrewType = 1
	CastAndCrewType_PRODUCER           CastAndCrewType = 2
	CastAndCrewType_WRITER             CastAndCrewType = 3
	CastAndCrewType_MUSIC_DIRECTOR     CastAndCrewType = 4
	CastAndCrewType_CINEMATOGRAPHER    CastAndCrewType = 5
	CastAndCrewType_EDITOR             CastAndCrewType = 6
	CastAndCrewType_ART_DIRECTOR       CastAndCrewType = 7
	CastAndCrewType_COSTUME_DESIGNER   CastAndCrewType = 8
	CastAndCrewType_MAKEUP_ARTIST      CastAndCrewType = 9
	CastAndCrewType_SOUND_DESIGNER     CastAndCrewType = 10
	CastAndCrewType_VFX_ARTIST         CastAndCrewType = 11
	CastAndCrewType_STUNT_PERFORMER    CastAndCrewType = 12
	CastAndCrewType_CHOREOGRAPHER      CastAndCrewType = 13
	CastAndCrewType_LYRICIST           CastAndCrewType = 14
	CastAndCrewType_PLAYBACK_SINGER    CastAndCrewType = 15
	CastAndCrewType_DUBBING_ARTIST     CastAndCrewType = 16
	CastAndCrewType_PUBLICITY_DESIGNER CastAndCrewType = 17
	CastAndCrewType_PUBLIC_RELATIONS   CastAndCrewType = 18
	CastAndCrewType_DISTRIBUTOR        CastAndCrewType = 19
	CastAndCrewType_MARKETING          CastAndCrewType = 20
	CastAndCrewType_LEGAL              CastAndCrewType = 21
	CastAndCrewType_FINANCE            CastAndCrewType = 22
	CastAndCrewType_PRODUCTION         CastAndCrewType = 23
	CastAndCrewType_OTHER              CastAndCrewType = 24
)

// Enum value maps for CastAndCrewType.
var (
	CastAndCrewType_name = map[int32]string{
		0:  "ACTOR",
		1:  "DIRECTOR",
		2:  "PRODUCER",
		3:  "WRITER",
		4:  "MUSIC_DIRECTOR",
		5:  "CINEMATOGRAPHER",
		6:  "EDITOR",
		7:  "ART_DIRECTOR",
		8:  "COSTUME_DESIGNER",
		9:  "MAKEUP_ARTIST",
		10: "SOUND_DESIGNER",
		11: "VFX_ARTIST",
		12: "STUNT_PERFORMER",
		13: "CHOREOGRAPHER",
		14: "LYRICIST",
		15: "PLAYBACK_SINGER",
		16: "DUBBING_ARTIST",
		17: "PUBLICITY_DESIGNER",
		18: "PUBLIC_RELATIONS",
		19: "DISTRIBUTOR",
		20: "MARKETING",
		21: "LEGAL",
		22: "FINANCE",
		23: "PRODUCTION",
		24: "OTHER",
	}
	CastAndCrewType_value = map[string]int32{
		"ACTOR":              0,
		"DIRECTOR":           1,
		"PRODUCER":           2,
		"WRITER":             3,
		"MUSIC_DIRECTOR":     4,
		"CINEMATOGRAPHER":    5,
		"EDITOR":             6,
		"ART_DIRECTOR":       7,
		"COSTUME_DESIGNER":   8,
		"MAKEUP_ARTIST":      9,
		"SOUND_DESIGNER":     10,
		"VFX_ARTIST":         11,
		"STUNT_PERFORMER":    12,
		"CHOREOGRAPHER":      13,
		"LYRICIST":           14,
		"PLAYBACK_SINGER":    15,
		"DUBBING_ARTIST":     16,
		"PUBLICITY_DESIGNER": 17,
		"PUBLIC_RELATIONS":   18,
		"DISTRIBUTOR":        19,
		"MARKETING":          20,
		"LEGAL":              21,
		"FINANCE":            22,
		"PRODUCTION":         23,
		"OTHER":              24,
	}
)

func (x CastAndCrewType) Enum() *CastAndCrewType {
	p := new(CastAndCrewType)
	*p = x
	return p
}

func (x CastAndCrewType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CastAndCrewType) Descriptor() protoreflect.EnumDescriptor {
	return file_moviedb_service_proto_enumTypes[0].Descriptor()
}

func (CastAndCrewType) Type() protoreflect.EnumType {
	return &file_moviedb_service_proto_enumTypes[0]
}

func (x CastAndCrewType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CastAndCrewType.Descriptor instead.
func (CastAndCrewType) EnumDescriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{0}
}

type VenueType int32

const (
	VenueType_MOVIE   VenueType = 0
	VenueType_CONCERT VenueType = 1
	VenueType_PLAY    VenueType = 2
	VenueType_STANDUP VenueType = 3
)

// Enum value maps for VenueType.
var (
	VenueType_name = map[int32]string{
		0: "MOVIE",
		1: "CONCERT",
		2: "PLAY",
		3: "STANDUP",
	}
	VenueType_value = map[string]int32{
		"MOVIE":   0,
		"CONCERT": 1,
		"PLAY":    2,
		"STANDUP": 3,
	}
)

func (x VenueType) Enum() *VenueType {
	p := new(VenueType)
	*p = x
	return p
}

func (x VenueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VenueType) Descriptor() protoreflect.EnumDescriptor {
	return file_moviedb_service_proto_enumTypes[1].Descriptor()
}

func (VenueType) Type() protoreflect.EnumType {
	return &file_moviedb_service_proto_enumTypes[1]
}

func (x VenueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VenueType.Descriptor instead.
func (VenueType) EnumDescriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{1}
}

type SeatType int32

const (
	SeatType_TWO_D   SeatType = 0
	SeatType_THREE_D SeatType = 1
	SeatType_FOUR_D  SeatType = 2
	SeatType_NORMAL  SeatType = 3
	SeatType_VIP     SeatType = 4
)

// Enum value maps for SeatType.
var (
	SeatType_name = map[int32]string{
		0: "TWO_D",
		1: "THREE_D",
		2: "FOUR_D",
		3: "NORMAL",
		4: "VIP",
	}
	SeatType_value = map[string]int32{
		"TWO_D":   0,
		"THREE_D": 1,
		"FOUR_D":  2,
		"NORMAL":  3,
		"VIP":     4,
	}
)

func (x SeatType) Enum() *SeatType {
	p := new(SeatType)
	*p = x
	return p
}

func (x SeatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeatType) Descriptor() protoreflect.EnumDescriptor {
	return file_moviedb_service_proto_enumTypes[2].Descriptor()
}

func (SeatType) Type() protoreflect.EnumType {
	return &file_moviedb_service_proto_enumTypes[2]
}

func (x SeatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeatType.Descriptor instead.
func (SeatType) EnumDescriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{2}
}

type SortBy int32

const (
	SortBy_ASCENDING  SortBy = 0
	SortBy_DESCENDING SortBy = 1
)

// Enum value maps for SortBy.
var (
	SortBy_name = map[int32]string{
		0: "ASCENDING",
		1: "DESCENDING",
	}
	SortBy_value = map[string]int32{
		"ASCENDING":  0,
		"DESCENDING": 1,
	}
)

func (x SortBy) Enum() *SortBy {
	p := new(SortBy)
	*p = x
	return p
}

func (x SortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_moviedb_service_proto_enumTypes[3].Descriptor()
}

func (SortBy) Type() protoreflect.EnumType {
	return &file_moviedb_service_proto_enumTypes[3]
}

func (x SortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortBy.Descriptor instead.
func (SortBy) EnumDescriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{3}
}

type FilterBy int32

const (
	FilterBy_RATING FilterBy = 0
	FilterBy_DATE   FilterBy = 1
)

// Enum value maps for FilterBy.
var (
	FilterBy_name = map[int32]string{
		0: "RATING",
		1: "DATE",
	}
	FilterBy_value = map[string]int32{
		"RATING": 0,
		"DATE":   1,
	}
)

func (x FilterBy) Enum() *FilterBy {
	p := new(FilterBy)
	*p = x
	return p
}

func (x FilterBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterBy) Descriptor() protoreflect.EnumDescriptor {
	return file_moviedb_service_proto_enumTypes[4].Descriptor()
}

func (FilterBy) Type() protoreflect.EnumType {
	return &file_moviedb_service_proto_enumTypes[4]
}

func (x FilterBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterBy.Descriptor instead.
func (FilterBy) EnumDescriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{4}
}

type CastAndCrew struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          CastAndCrewType        `protobuf:"varint,2,opt,name=type,proto3,enum=moviedb_service.CastAndCrewType" json:"type,omitempty"`
	CharacterName string                 `protobuf:"bytes,3,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	Photourl      string                 `protobuf:"bytes,4,opt,name=photourl,proto3" json:"photourl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastAndCrew) Reset() {
	*x = CastAndCrew{}
	mi := &file_moviedb_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastAndCrew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastAndCrew) ProtoMessage() {}

func (x *CastAndCrew) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastAndCrew.ProtoReflect.Descriptor instead.
func (*CastAndCrew) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{0}
}

func (x *CastAndCrew) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CastAndCrew) GetType() CastAndCrewType {
	if x != nil {
		return x.Type
	}
	return CastAndCrewType_ACTOR
}

func (x *CastAndCrew) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *CastAndCrew) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

type MovieTimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	MovieFormat   SeatType               `protobuf:"varint,5,opt,name=movie_format,json=movieFormat,proto3,enum=moviedb_service.SeatType" json:"movie_format,omitempty"`
	Movieid       int32                  `protobuf:"varint,6,opt,name=movieid,proto3" json:"movieid,omitempty"`
	Venueid       int32                  `protobuf:"varint,7,opt,name=venueid,proto3" json:"venueid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieTimeSlot) Reset() {
	*x = MovieTimeSlot{}
	mi := &file_moviedb_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieTimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieTimeSlot) ProtoMessage() {}

func (x *MovieTimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieTimeSlot.ProtoReflect.Descriptor instead.
func (*MovieTimeSlot) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{1}
}

func (x *MovieTimeSlot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *MovieTimeSlot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *MovieTimeSlot) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MovieTimeSlot) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MovieTimeSlot) GetMovieFormat() SeatType {
	if x != nil {
		return x.MovieFormat
	}
	return SeatType_TWO_D
}

func (x *MovieTimeSlot) GetMovieid() int32 {
	if x != nil {
		return x.Movieid
	}
	return 0
}

func (x *MovieTimeSlot) GetVenueid() int32 {
	if x != nil {
		return x.Venueid
	}
	return 0
}

type Movie struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Duration        int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Language        []string               `protobuf:"bytes,4,rep,name=language,proto3" json:"language,omitempty"`
	Type            []string               `protobuf:"bytes,5,rep,name=type,proto3" json:"type,omitempty"`
	CastCrew        []*CastAndCrew         `protobuf:"bytes,6,rep,name=cast_crew,json=castCrew,proto3" json:"cast_crew,omitempty"`
	PosterUrl       string                 `protobuf:"bytes,7,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	TrailerUrl      string                 `protobuf:"bytes,8,opt,name=trailer_url,json=trailerUrl,proto3" json:"trailer_url,omitempty"`
	ReleaseDate     string                 `protobuf:"bytes,9,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	MovieResolution []string               `protobuf:"bytes,10,rep,name=movie_resolution,json=movieResolution,proto3" json:"movie_resolution,omitempty"`
	Venues          []*Venue               `protobuf:"bytes,11,rep,name=venues,proto3" json:"venues,omitempty"`
	// string movieid = 12;
	Votes         int64 `protobuf:"varint,13,opt,name=votes,proto3" json:"votes,omitempty"`
	Ranking       int32 `protobuf:"varint,14,opt,name=ranking,proto3" json:"ranking,omitempty"`
	Id            int32 `protobuf:"varint,15,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_moviedb_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{2}
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Movie) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Movie) GetLanguage() []string {
	if x != nil {
		return x.Language
	}
	return nil
}

func (x *Movie) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Movie) GetCastCrew() []*CastAndCrew {
	if x != nil {
		return x.CastCrew
	}
	return nil
}

func (x *Movie) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *Movie) GetTrailerUrl() string {
	if x != nil {
		return x.TrailerUrl
	}
	return ""
}

func (x *Movie) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Movie) GetMovieResolution() []string {
	if x != nil {
		return x.MovieResolution
	}
	return nil
}

func (x *Movie) GetVenues() []*Venue {
	if x != nil {
		return x.Venues
	}
	return nil
}

func (x *Movie) GetVotes() int64 {
	if x != nil {
		return x.Votes
	}
	return 0
}

func (x *Movie) GetRanking() int32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *Movie) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SeatMatrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatNumber    string                 `protobuf:"bytes,1,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	IsBooked      bool                   `protobuf:"varint,2,opt,name=is_booked,json=isBooked,proto3" json:"is_booked,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Row           int32                  `protobuf:"varint,4,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	Type          SeatType               `protobuf:"varint,6,opt,name=type,proto3,enum=moviedb_service.SeatType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatMatrix) Reset() {
	*x = SeatMatrix{}
	mi := &file_moviedb_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatMatrix) ProtoMessage() {}

func (x *SeatMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatMatrix.ProtoReflect.Descriptor instead.
func (*SeatMatrix) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{3}
}

func (x *SeatMatrix) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *SeatMatrix) GetIsBooked() bool {
	if x != nil {
		return x.IsBooked
	}
	return false
}

func (x *SeatMatrix) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SeatMatrix) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *SeatMatrix) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *SeatMatrix) GetType() SeatType {
	if x != nil {
		return x.Type
	}
	return SeatType_TWO_D
}

type Venue struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Type                 VenueType              `protobuf:"varint,3,opt,name=type,proto3,enum=moviedb_service.VenueType" json:"type,omitempty"`
	Rows                 int32                  `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns              int32                  `protobuf:"varint,5,opt,name=columns,proto3" json:"columns,omitempty"`
	Longitude            float32                `protobuf:"fixed32,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float32                `protobuf:"fixed32,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	ScreenNumber         int32                  `protobuf:"varint,8,opt,name=screen_number,json=screenNumber,proto3" json:"screen_number,omitempty"`
	Seats                []*SeatMatrix          `protobuf:"bytes,9,rep,name=seats,proto3" json:"seats,omitempty"`
	MovieTimeSlots       []*MovieTimeSlot       `protobuf:"bytes,10,rep,name=movie_time_slots,json=movieTimeSlots,proto3" json:"movie_time_slots,omitempty"`
	Movies               []*Movie               `protobuf:"bytes,11,rep,name=movies,proto3" json:"movies,omitempty"`
	Id                   int32                  `protobuf:"varint,12,opt,name=id,proto3" json:"id,omitempty"`
	MovieFormatSupported []string               `protobuf:"bytes,13,rep,name=movie_format_supported,json=movieFormatSupported,proto3" json:"movie_format_supported,omitempty"`
	LanguageSupported    []string               `protobuf:"bytes,14,rep,name=language_supported,json=languageSupported,proto3" json:"language_supported,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Venue) Reset() {
	*x = Venue{}
	mi := &file_moviedb_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Venue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Venue) ProtoMessage() {}

func (x *Venue) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Venue.ProtoReflect.Descriptor instead.
func (*Venue) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{4}
}

func (x *Venue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Venue) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Venue) GetType() VenueType {
	if x != nil {
		return x.Type
	}
	return VenueType_MOVIE
}

func (x *Venue) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Venue) GetColumns() int32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *Venue) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Venue) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Venue) GetScreenNumber() int32 {
	if x != nil {
		return x.ScreenNumber
	}
	return 0
}

func (x *Venue) GetSeats() []*SeatMatrix {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *Venue) GetMovieTimeSlots() []*MovieTimeSlot {
	if x != nil {
		return x.MovieTimeSlots
	}
	return nil
}

func (x *Venue) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *Venue) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Venue) GetMovieFormatSupported() []string {
	if x != nil {
		return x.MovieFormatSupported
	}
	return nil
}

func (x *Venue) GetLanguageSupported() []string {
	if x != nil {
		return x.LanguageSupported
	}
	return nil
}

type MovieList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieList) Reset() {
	*x = MovieList{}
	mi := &file_moviedb_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieList) ProtoMessage() {}

func (x *MovieList) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieList.ProtoReflect.Descriptor instead.
func (*MovieList) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{5}
}

func (x *MovieList) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type MovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Movieid       string                 `protobuf:"bytes,2,opt,name=movieid,proto3" json:"movieid,omitempty"`
	Venueid       string                 `protobuf:"bytes,3,opt,name=venueid,proto3" json:"venueid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieRequest) Reset() {
	*x = MovieRequest{}
	mi := &file_moviedb_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieRequest) ProtoMessage() {}

func (x *MovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieRequest.ProtoReflect.Descriptor instead.
func (*MovieRequest) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{6}
}

func (x *MovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieRequest) GetMovieid() string {
	if x != nil {
		return x.Movieid
	}
	return ""
}

func (x *MovieRequest) GetVenueid() string {
	if x != nil {
		return x.Venueid
	}
	return ""
}

type MovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Movie         *Movie                 `protobuf:"bytes,3,opt,name=movie,proto3" json:"movie,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieResponse) Reset() {
	*x = MovieResponse{}
	mi := &file_moviedb_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieResponse) ProtoMessage() {}

func (x *MovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieResponse.ProtoReflect.Descriptor instead.
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{7}
}

func (x *MovieResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MovieResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MovieResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

func (x *MovieResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MovieListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MovieList     *MovieList             `protobuf:"bytes,3,opt,name=movie_list,json=movieList,proto3" json:"movie_list,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieListResponse) Reset() {
	*x = MovieListResponse{}
	mi := &file_moviedb_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieListResponse) ProtoMessage() {}

func (x *MovieListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieListResponse.ProtoReflect.Descriptor instead.
func (*MovieListResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{8}
}

func (x *MovieListResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MovieListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MovieListResponse) GetMovieList() *MovieList {
	if x != nil {
		return x.MovieList
	}
	return nil
}

func (x *MovieListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Venue         *Venue                 `protobuf:"bytes,3,opt,name=Venue,proto3" json:"Venue,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VenueResponse) Reset() {
	*x = VenueResponse{}
	mi := &file_moviedb_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VenueResponse) ProtoMessage() {}

func (x *VenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VenueResponse.ProtoReflect.Descriptor instead.
func (*VenueResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{9}
}

func (x *VenueResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VenueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VenueResponse) GetVenue() *Venue {
	if x != nil {
		return x.Venue
	}
	return nil
}

func (x *VenueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUpcomingMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingMovieRequest) Reset() {
	*x = GetUpcomingMovieRequest{}
	mi := &file_moviedb_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingMovieRequest) ProtoMessage() {}

func (x *GetUpcomingMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingMovieRequest.ProtoReflect.Descriptor instead.
func (*GetUpcomingMovieRequest) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetUpcomingMovieRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetUpcomingMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MovieList     []*Movie               `protobuf:"bytes,3,rep,name=movie_list,json=movieList,proto3" json:"movie_list,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingMovieResponse) Reset() {
	*x = GetUpcomingMovieResponse{}
	mi := &file_moviedb_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingMovieResponse) ProtoMessage() {}

func (x *GetUpcomingMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingMovieResponse.ProtoReflect.Descriptor instead.
func (*GetUpcomingMovieResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetUpcomingMovieResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetUpcomingMovieResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUpcomingMovieResponse) GetMovieList() []*Movie {
	if x != nil {
		return x.MovieList
	}
	return nil
}

func (x *GetUpcomingMovieResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetNowPlayingMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     int64                  `protobuf:"varint,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      int64                  `protobuf:"varint,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNowPlayingMovieRequest) Reset() {
	*x = GetNowPlayingMovieRequest{}
	mi := &file_moviedb_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNowPlayingMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNowPlayingMovieRequest) ProtoMessage() {}

func (x *GetNowPlayingMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNowPlayingMovieRequest.ProtoReflect.Descriptor instead.
func (*GetNowPlayingMovieRequest) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetNowPlayingMovieRequest) GetLongitude() int64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetNowPlayingMovieRequest) GetLatitude() int64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieID       int32                  `protobuf:"varint,1,opt,name=movieID,proto3" json:"movieID,omitempty"`
	UserID        int32                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	ReviewID      int32                  `protobuf:"varint,6,opt,name=reviewID,proto3" json:"reviewID,omitempty"`
	CreatedAt     int32                  `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ReviewerName  string                 `protobuf:"bytes,8,opt,name=reviewerName,proto3" json:"reviewerName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_moviedb_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{13}
}

func (x *Review) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *Review) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Review) GetReviewID() int32 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *Review) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Review) GetReviewerName() string {
	if x != nil {
		return x.ReviewerName
	}
	return ""
}

type ReviewUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ReviewID      int32                  `protobuf:"varint,2,opt,name=reviewID,proto3" json:"reviewID,omitempty"`
	MovieID       int32                  `protobuf:"varint,3,opt,name=movieID,proto3" json:"movieID,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Rating        int32                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewUpdateRequest) Reset() {
	*x = ReviewUpdateRequest{}
	mi := &file_moviedb_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewUpdateRequest) ProtoMessage() {}

func (x *ReviewUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewUpdateRequest.ProtoReflect.Descriptor instead.
func (*ReviewUpdateRequest) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{14}
}

func (x *ReviewUpdateRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ReviewUpdateRequest) GetReviewID() int32 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *ReviewUpdateRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *ReviewUpdateRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ReviewUpdateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReviewUpdateRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Review        *Review                `protobuf:"bytes,3,opt,name=review,proto3" json:"review,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_moviedb_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{15}
}

func (x *ReviewResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ReviewResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *ReviewResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ReviewID      int32                  `protobuf:"varint,2,opt,name=reviewID,proto3" json:"reviewID,omitempty"`
	MovieID       int32                  `protobuf:"varint,3,opt,name=movieID,proto3" json:"movieID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewRequest) Reset() {
	*x = ReviewRequest{}
	mi := &file_moviedb_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRequest) ProtoMessage() {}

func (x *ReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRequest.ProtoReflect.Descriptor instead.
func (*ReviewRequest) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{16}
}

func (x *ReviewRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ReviewRequest) GetReviewID() int32 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *ReviewRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

type ReviewList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewList) Reset() {
	*x = ReviewList{}
	mi := &file_moviedb_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewList) ProtoMessage() {}

func (x *ReviewList) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewList.ProtoReflect.Descriptor instead.
func (*ReviewList) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{17}
}

func (x *ReviewList) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type ReviewListResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ReviewList       *ReviewList            `protobuf:"bytes,3,opt,name=review_list,json=reviewList,proto3" json:"review_list,omitempty"`
	Error            string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	TotalReviewCount int32                  `protobuf:"varint,5,opt,name=totalReviewCount,proto3" json:"totalReviewCount,omitempty"`
	TotalVotes       int32                  `protobuf:"varint,6,opt,name=totalVotes,proto3" json:"totalVotes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReviewListResponse) Reset() {
	*x = ReviewListResponse{}
	mi := &file_moviedb_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewListResponse) ProtoMessage() {}

func (x *ReviewListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewListResponse.ProtoReflect.Descriptor instead.
func (*ReviewListResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{18}
}

func (x *ReviewListResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ReviewListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReviewListResponse) GetReviewList() *ReviewList {
	if x != nil {
		return x.ReviewList
	}
	return nil
}

func (x *ReviewListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReviewListResponse) GetTotalReviewCount() int32 {
	if x != nil {
		return x.TotalReviewCount
	}
	return 0
}

func (x *ReviewListResponse) GetTotalVotes() int32 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

type GetAllMovieReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieID       int32                  `protobuf:"varint,1,opt,name=movieID,proto3" json:"movieID,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	SortBy        SortBy                 `protobuf:"varint,5,opt,name=sortBy,proto3,enum=moviedb_service.SortBy" json:"sortBy,omitempty"`
	FilterBy      FilterBy               `protobuf:"varint,6,opt,name=filterBy,proto3,enum=moviedb_service.FilterBy" json:"filterBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMovieReviewsRequest) Reset() {
	*x = GetAllMovieReviewsRequest{}
	mi := &file_moviedb_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMovieReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMovieReviewsRequest) ProtoMessage() {}

func (x *GetAllMovieReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMovieReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetAllMovieReviewsRequest) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetAllMovieReviewsRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *GetAllMovieReviewsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllMovieReviewsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetAllMovieReviewsRequest) GetSortBy() SortBy {
	if x != nil {
		return x.SortBy
	}
	return SortBy_ASCENDING
}

func (x *GetAllMovieReviewsRequest) GetFilterBy() FilterBy {
	if x != nil {
		return x.FilterBy
	}
	return FilterBy_RATING
}

type GetMovieTimeSlotRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Movieid   string                 `protobuf:"bytes,1,opt,name=movieid,proto3" json:"movieid,omitempty"`
	StartDate string                 `protobuf:"bytes,3,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate   string                 `protobuf:"bytes,4,opt,name=endDate,proto3" json:"endDate,omitempty"`
	// Deprecated: Marked as deprecated in moviedb_service.proto.
	OldLongitude int64 `protobuf:"varint,5,opt,name=old_longitude,json=oldLongitude,proto3" json:"old_longitude,omitempty"`
	// Deprecated: Marked as deprecated in moviedb_service.proto.
	OldLatitude   int64   `protobuf:"varint,6,opt,name=old_latitude,json=oldLatitude,proto3" json:"old_latitude,omitempty"`
	Longitude     float32 `protobuf:"fixed32,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float32 `protobuf:"fixed32,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieTimeSlotRequest) Reset() {
	*x = GetMovieTimeSlotRequest{}
	mi := &file_moviedb_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieTimeSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieTimeSlotRequest) ProtoMessage() {}

func (x *GetMovieTimeSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieTimeSlotRequest.ProtoReflect.Descriptor instead.
func (*GetMovieTimeSlotRequest) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetMovieTimeSlotRequest) GetMovieid() string {
	if x != nil {
		return x.Movieid
	}
	return ""
}

func (x *GetMovieTimeSlotRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetMovieTimeSlotRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// Deprecated: Marked as deprecated in moviedb_service.proto.
func (x *GetMovieTimeSlotRequest) GetOldLongitude() int64 {
	if x != nil {
		return x.OldLongitude
	}
	return 0
}

// Deprecated: Marked as deprecated in moviedb_service.proto.
func (x *GetMovieTimeSlotRequest) GetOldLatitude() int64 {
	if x != nil {
		return x.OldLatitude
	}
	return 0
}

func (x *GetMovieTimeSlotRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetMovieTimeSlotRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type GetMovieTimeSlotResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MovieTimeSlots []*MovieTimeSlot       `protobuf:"bytes,3,rep,name=movie_time_slots,json=movieTimeSlots,proto3" json:"movie_time_slots,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Venues         []*Venue               `protobuf:"bytes,5,rep,name=venues,proto3" json:"venues,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMovieTimeSlotResponse) Reset() {
	*x = GetMovieTimeSlotResponse{}
	mi := &file_moviedb_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieTimeSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieTimeSlotResponse) ProtoMessage() {}

func (x *GetMovieTimeSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieTimeSlotResponse.ProtoReflect.Descriptor instead.
func (*GetMovieTimeSlotResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetMovieTimeSlotResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetMovieTimeSlotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMovieTimeSlotResponse) GetMovieTimeSlots() []*MovieTimeSlot {
	if x != nil {
		return x.MovieTimeSlots
	}
	return nil
}

func (x *GetMovieTimeSlotResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetMovieTimeSlotResponse) GetVenues() []*Venue {
	if x != nil {
		return x.Venues
	}
	return nil
}

type MovieTimeSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieTimeSlotResponse) Reset() {
	*x = MovieTimeSlotResponse{}
	mi := &file_moviedb_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieTimeSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieTimeSlotResponse) ProtoMessage() {}

func (x *MovieTimeSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieTimeSlotResponse.ProtoReflect.Descriptor instead.
func (*MovieTimeSlotResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{22}
}

func (x *MovieTimeSlotResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MovieTimeSlotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MovieTimeSlotResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MovieTimeSlotUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MovieTimeSlot *MovieTimeSlot         `protobuf:"bytes,3,opt,name=movie_time_slot,json=movieTimeSlot,proto3" json:"movie_time_slot,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieTimeSlotUpdateResponse) Reset() {
	*x = MovieTimeSlotUpdateResponse{}
	mi := &file_moviedb_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieTimeSlotUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieTimeSlotUpdateResponse) ProtoMessage() {}

func (x *MovieTimeSlotUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieTimeSlotUpdateResponse.ProtoReflect.Descriptor instead.
func (*MovieTimeSlotUpdateResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{23}
}

func (x *MovieTimeSlotUpdateResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MovieTimeSlotUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MovieTimeSlotUpdateResponse) GetMovieTimeSlot() *MovieTimeSlot {
	if x != nil {
		return x.MovieTimeSlot
	}
	return nil
}

func (x *MovieTimeSlotUpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MovieTimeSlotUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StartTime       string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration        int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Date            string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	MovieFormat     SeatType               `protobuf:"varint,5,opt,name=movie_format,json=movieFormat,proto3,enum=moviedb_service.SeatType" json:"movie_format,omitempty"`
	Movieid         int32                  `protobuf:"varint,6,opt,name=movieid,proto3" json:"movieid,omitempty"`
	Venueid         int32                  `protobuf:"varint,7,opt,name=venueid,proto3" json:"venueid,omitempty"`
	MovieTimeSlotId int32                  `protobuf:"varint,8,opt,name=movie_time_slot_id,json=movieTimeSlotId,proto3" json:"movie_time_slot_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MovieTimeSlotUpdate) Reset() {
	*x = MovieTimeSlotUpdate{}
	mi := &file_moviedb_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieTimeSlotUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieTimeSlotUpdate) ProtoMessage() {}

func (x *MovieTimeSlotUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieTimeSlotUpdate.ProtoReflect.Descriptor instead.
func (*MovieTimeSlotUpdate) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{24}
}

func (x *MovieTimeSlotUpdate) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *MovieTimeSlotUpdate) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *MovieTimeSlotUpdate) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MovieTimeSlotUpdate) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MovieTimeSlotUpdate) GetMovieFormat() SeatType {
	if x != nil {
		return x.MovieFormat
	}
	return SeatType_TWO_D
}

func (x *MovieTimeSlotUpdate) GetMovieid() int32 {
	if x != nil {
		return x.Movieid
	}
	return 0
}

func (x *MovieTimeSlotUpdate) GetVenueid() int32 {
	if x != nil {
		return x.Venueid
	}
	return 0
}

func (x *MovieTimeSlotUpdate) GetMovieTimeSlotId() int32 {
	if x != nil {
		return x.MovieTimeSlotId
	}
	return 0
}

type MovieTimeSlotDelete struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MovieTimeSlotId int32                  `protobuf:"varint,1,opt,name=movie_time_slot_id,json=movieTimeSlotId,proto3" json:"movie_time_slot_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MovieTimeSlotDelete) Reset() {
	*x = MovieTimeSlotDelete{}
	mi := &file_moviedb_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieTimeSlotDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieTimeSlotDelete) ProtoMessage() {}

func (x *MovieTimeSlotDelete) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieTimeSlotDelete.ProtoReflect.Descriptor instead.
func (*MovieTimeSlotDelete) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{25}
}

func (x *MovieTimeSlotDelete) GetMovieTimeSlotId() int32 {
	if x != nil {
		return x.MovieTimeSlotId
	}
	return 0
}

var File_moviedb_service_proto protoreflect.FileDescriptor

const file_moviedb_service_proto_rawDesc = "" +
	"\n" +
	"\x15moviedb_service.proto\x12\x0fmoviedb_service\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x01\n" +
	"\vCastAndCrew\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .moviedb_service.CastAndCrewTypeR\x04type\x12%\n" +
	"\x0echaracter_name\x18\x03 \x01(\tR\rcharacterName\x12\x1a\n" +
	"\bphotourl\x18\x04 \x01(\tR\bphotourl\"\xeb\x01\n" +
	"\rMovieTimeSlot\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12<\n" +
	"\fmovie_format\x18\x05 \x01(\x0e2\x19.moviedb_service.SeatTypeR\vmovieFormat\x12\x18\n" +
	"\amovieid\x18\x06 \x01(\x05R\amovieid\x12\x18\n" +
	"\avenueid\x18\a \x01(\x05R\avenueid\"\xc4\x03\n" +
	"\x05Movie\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x1a\n" +
	"\blanguage\x18\x04 \x03(\tR\blanguage\x12\x12\n" +
	"\x04type\x18\x05 \x03(\tR\x04type\x129\n" +
	"\tcast_crew\x18\x06 \x03(\v2\x1c.moviedb_service.CastAndCrewR\bcastCrew\x12\x1d\n" +
	"\n" +
	"poster_url\x18\a \x01(\tR\tposterUrl\x12\x1f\n" +
	"\vtrailer_url\x18\b \x01(\tR\n" +
	"trailerUrl\x12!\n" +
	"\frelease_date\x18\t \x01(\tR\vreleaseDate\x12)\n" +
	"\x10movie_resolution\x18\n" +
	" \x03(\tR\x0fmovieResolution\x12.\n" +
	"\x06venues\x18\v \x03(\v2\x16.moviedb_service.VenueR\x06venues\x12\x14\n" +
	"\x05votes\x18\r \x01(\x03R\x05votes\x12\x18\n" +
	"\aranking\x18\x0e \x01(\x05R\aranking\x12\x0e\n" +
	"\x02id\x18\x0f \x01(\x05R\x02id\"\xb9\x01\n" +
	"\n" +
	"SeatMatrix\x12\x1f\n" +
	"\vseat_number\x18\x01 \x01(\tR\n" +
	"seatNumber\x12\x1b\n" +
	"\tis_booked\x18\x02 \x01(\bR\bisBooked\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x10\n" +
	"\x03row\x18\x04 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\x12-\n" +
	"\x04type\x18\x06 \x01(\x0e2\x19.moviedb_service.SeatTypeR\x04type\"\x94\x04\n" +
	"\x05Venue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.moviedb_service.VenueTypeR\x04type\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x05R\x04rows\x12\x18\n" +
	"\acolumns\x18\x05 \x01(\x05R\acolumns\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x02R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x02R\blatitude\x12#\n" +
	"\rscreen_number\x18\b \x01(\x05R\fscreenNumber\x121\n" +
	"\x05seats\x18\t \x03(\v2\x1b.moviedb_service.SeatMatrixR\x05seats\x12H\n" +
	"\x10movie_time_slots\x18\n" +
	" \x03(\v2\x1e.moviedb_service.MovieTimeSlotR\x0emovieTimeSlots\x12.\n" +
	"\x06movies\x18\v \x03(\v2\x16.moviedb_service.MovieR\x06movies\x12\x0e\n" +
	"\x02id\x18\f \x01(\x05R\x02id\x124\n" +
	"\x16movie_format_supported\x18\r \x03(\tR\x14movieFormatSupported\x12-\n" +
	"\x12language_supported\x18\x0e \x03(\tR\x11languageSupported\";\n" +
	"\tMovieList\x12.\n" +
	"\x06movies\x18\x01 \x03(\v2\x16.moviedb_service.MovieR\x06movies\"X\n" +
	"\fMovieRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amovieid\x18\x02 \x01(\tR\amovieid\x12\x18\n" +
	"\avenueid\x18\x03 \x01(\tR\avenueid\"\x85\x01\n" +
	"\rMovieResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x05movie\x18\x03 \x01(\v2\x16.moviedb_service.MovieR\x05movie\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x96\x01\n" +
	"\x11MovieListResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"movie_list\x18\x03 \x01(\v2\x1a.moviedb_service.MovieListR\tmovieList\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x85\x01\n" +
	"\rVenueResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x05Venue\x18\x03 \x01(\v2\x16.moviedb_service.VenueR\x05Venue\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"-\n" +
	"\x17GetUpcomingMovieRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"\x99\x01\n" +
	"\x18GetUpcomingMovieResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\n" +
	"movie_list\x18\x03 \x03(\v2\x16.moviedb_service.MovieR\tmovieList\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"U\n" +
	"\x19GetNowPlayingMovieRequest\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x03R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x03R\blatitude\"\xe0\x01\n" +
	"\x06Review\x12\x18\n" +
	"\amovieID\x18\x01 \x01(\x05R\amovieID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x05R\x06userID\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1a\n" +
	"\breviewID\x18\x06 \x01(\x05R\breviewID\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\x05R\tcreatedAt\x12\"\n" +
	"\freviewerName\x18\b \x01(\tR\freviewerName\"\xab\x01\n" +
	"\x13ReviewUpdateRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x1a\n" +
	"\breviewID\x18\x02 \x01(\x05R\breviewID\x12\x18\n" +
	"\amovieID\x18\x03 \x01(\x05R\amovieID\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x05R\x06rating\"\x89\x01\n" +
	"\x0eReviewResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x06review\x18\x03 \x01(\v2\x17.moviedb_service.ReviewR\x06review\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"]\n" +
	"\rReviewRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x1a\n" +
	"\breviewID\x18\x02 \x01(\x05R\breviewID\x12\x18\n" +
	"\amovieID\x18\x03 \x01(\x05R\amovieID\"?\n" +
	"\n" +
	"ReviewList\x121\n" +
	"\areviews\x18\x01 \x03(\v2\x17.moviedb_service.ReviewR\areviews\"\xe6\x01\n" +
	"\x12ReviewListResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\vreview_list\x18\x03 \x01(\v2\x1b.moviedb_service.ReviewListR\n" +
	"reviewList\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12*\n" +
	"\x10totalReviewCount\x18\x05 \x01(\x05R\x10totalReviewCount\x12\x1e\n" +
	"\n" +
	"totalVotes\x18\x06 \x01(\x05R\n" +
	"totalVotes\"\xcb\x01\n" +
	"\x19GetAllMovieReviewsRequest\x12\x18\n" +
	"\amovieID\x18\x01 \x01(\x05R\amovieID\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12/\n" +
	"\x06sortBy\x18\x05 \x01(\x0e2\x17.moviedb_service.SortByR\x06sortBy\x125\n" +
	"\bfilterBy\x18\x06 \x01(\x0e2\x19.moviedb_service.FilterByR\bfilterBy\"\xfb\x01\n" +
	"\x17GetMovieTimeSlotRequest\x12\x18\n" +
	"\amovieid\x18\x01 \x01(\tR\amovieid\x12\x1c\n" +
	"\tstartDate\x18\x03 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x04 \x01(\tR\aendDate\x12'\n" +
	"\rold_longitude\x18\x05 \x01(\x03B\x02\x18\x01R\foldLongitude\x12%\n" +
	"\fold_latitude\x18\x06 \x01(\x03B\x02\x18\x01R\voldLatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x02R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\b \x01(\x02R\blatitudeJ\x04\b\x02\x10\x03\"\xdc\x01\n" +
	"\x18GetMovieTimeSlotResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12H\n" +
	"\x10movie_time_slots\x18\x03 \x03(\v2\x1e.moviedb_service.MovieTimeSlotR\x0emovieTimeSlots\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12.\n" +
	"\x06venues\x18\x05 \x03(\v2\x16.moviedb_service.VenueR\x06venues\"_\n" +
	"\x15MovieTimeSlotResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xad\x01\n" +
	"\x1bMovieTimeSlotUpdateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\x0fmovie_time_slot\x18\x03 \x01(\v2\x1e.moviedb_service.MovieTimeSlotR\rmovieTimeSlot\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x9e\x02\n" +
	"\x13MovieTimeSlotUpdate\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12<\n" +
	"\fmovie_format\x18\x05 \x01(\x0e2\x19.moviedb_service.SeatTypeR\vmovieFormat\x12\x18\n" +
	"\amovieid\x18\x06 \x01(\x05R\amovieid\x12\x18\n" +
	"\avenueid\x18\a \x01(\x05R\avenueid\x12+\n" +
	"\x12movie_time_slot_id\x18\b \x01(\x05R\x0fmovieTimeSlotId\"B\n" +
	"\x13MovieTimeSlotDelete\x12+\n" +
	"\x12movie_time_slot_id\x18\x01 \x01(\x05R\x0fmovieTimeSlotId*\xb8\x03\n" +
	"\x0fCastAndCrewType\x12\t\n" +
	"\x05ACTOR\x10\x00\x12\f\n" +
	"\bDIRECTOR\x10\x01\x12\f\n" +
	"\bPRODUCER\x10\x02\x12\n" +
	"\n" +
	"\x06WRITER\x10\x03\x12\x12\n" +
	"\x0eMUSIC_DIRECTOR\x10\x04\x12\x13\n" +
	"\x0fCINEMATOGRAPHER\x10\x05\x12\n" +
	"\n" +
	"\x06EDITOR\x10\x06\x12\x10\n" +
	"\fART_DIRECTOR\x10\a\x12\x14\n" +
	"\x10COSTUME_DESIGNER\x10\b\x12\x11\n" +
	"\rMAKEUP_ARTIST\x10\t\x12\x12\n" +
	"\x0eSOUND_DESIGNER\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"VFX_ARTIST\x10\v\x12\x13\n" +
	"\x0fSTUNT_PERFORMER\x10\f\x12\x11\n" +
	"\rCHOREOGRAPHER\x10\r\x12\f\n" +
	"\bLYRICIST\x10\x0e\x12\x13\n" +
	"\x0fPLAYBACK_SINGER\x10\x0f\x12\x12\n" +
	"\x0eDUBBING_ARTIST\x10\x10\x12\x16\n" +
	"\x12PUBLICITY_DESIGNER\x10\x11\x12\x14\n" +
	"\x10PUBLIC_RELATIONS\x10\x12\x12\x0f\n" +
	"\vDISTRIBUTOR\x10\x13\x12\r\n" +
	"\tMARKETING\x10\x14\x12\t\n" +
	"\x05LEGAL\x10\x15\x12\v\n" +
	"\aFINANCE\x10\x16\x12\x0e\n" +
	"\n" +
	"PRODUCTION\x10\x17\x12\t\n" +
	"\x05OTHER\x10\x18*:\n" +
	"\tVenueType\x12\t\n" +
	"\x05MOVIE\x10\x00\x12\v\n" +
	"\aCONCERT\x10\x01\x12\b\n" +
	"\x04PLAY\x10\x02\x12\v\n" +
	"\aSTANDUP\x10\x03*C\n" +
	"\bSeatType\x12\t\n" +
	"\x05TWO_D\x10\x00\x12\v\n" +
	"\aTHREE_D\x10\x01\x12\n" +
	"\n" +
	"\x06FOUR_D\x10\x02\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x03\x12\a\n" +
	"\x03VIP\x10\x04*'\n" +
	"\x06SortBy\x12\r\n" +
	"\tASCENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"DESCENDING\x10\x01* \n" +
	"\bFilterBy\x12\n" +
	"\n" +
	"\x06RATING\x10\x00\x12\b\n" +
	"\x04DATE\x10\x012\x82\x0e\n" +
	"\x0eMovieDBService\x12B\n" +
	"\bAddMovie\x12\x16.moviedb_service.Movie\x1a\x1e.moviedb_service.MovieResponse\x12I\n" +
	"\bGetMovie\x12\x1d.moviedb_service.MovieRequest\x1a\x1e.moviedb_service.MovieResponse\x12J\n" +
	"\fGetAllMovies\x12\x16.google.protobuf.Empty\x1a\".moviedb_service.MovieListResponse\x12E\n" +
	"\vUpdateMovie\x12\x16.moviedb_service.Movie\x1a\x1e.moviedb_service.MovieResponse\x12L\n" +
	"\vDeleteMovie\x12\x1d.moviedb_service.MovieRequest\x1a\x1e.moviedb_service.MovieResponse\x12B\n" +
	"\bAddVenue\x12\x16.moviedb_service.Venue\x1a\x1e.moviedb_service.VenueResponse\x12I\n" +
	"\bGetVenue\x12\x1d.moviedb_service.MovieRequest\x1a\x1e.moviedb_service.VenueResponse\x12J\n" +
	"\fGetAllVenues\x12\x16.google.protobuf.Empty\x1a\".moviedb_service.MovieListResponse\x12E\n" +
	"\vUpdateVenue\x12\x16.moviedb_service.Venue\x1a\x1e.moviedb_service.VenueResponse\x12L\n" +
	"\vDeleteVenue\x12\x1d.moviedb_service.MovieRequest\x1a\x1e.moviedb_service.MovieResponse\x12h\n" +
	"\x11GetUpcomingMovies\x12(.moviedb_service.GetUpcomingMovieRequest\x1a).moviedb_service.GetUpcomingMovieResponse\x12l\n" +
	"\x13GetNowPlayingMovies\x12*.moviedb_service.GetNowPlayingMovieRequest\x1a).moviedb_service.GetUpcomingMovieResponse\x12E\n" +
	"\tAddReview\x12\x17.moviedb_service.Review\x1a\x1f.moviedb_service.ReviewResponse\x12L\n" +
	"\tGetReview\x12\x1e.moviedb_service.ReviewRequest\x1a\x1f.moviedb_service.ReviewResponse\x12U\n" +
	"\fUpdateReview\x12$.moviedb_service.ReviewUpdateRequest\x1a\x1f.moviedb_service.ReviewResponse\x12O\n" +
	"\fDeleteReview\x12\x1e.moviedb_service.ReviewRequest\x1a\x1f.moviedb_service.ReviewResponse\x12e\n" +
	"\x12GetAllMovieReviews\x12*.moviedb_service.GetAllMovieReviewsRequest\x1a#.moviedb_service.ReviewListResponse\x12h\n" +
	"\x11GetMovieTimeSlots\x12(.moviedb_service.GetMovieTimeSlotRequest\x1a).moviedb_service.GetMovieTimeSlotResponse\x12Z\n" +
	"\x10AddMovieTimeSlot\x12\x1e.moviedb_service.MovieTimeSlot\x1a&.moviedb_service.MovieTimeSlotResponse\x12i\n" +
	"\x13UpdateMovieTimeSlot\x12$.moviedb_service.MovieTimeSlotUpdate\x1a,.moviedb_service.MovieTimeSlotUpdateResponse\x12c\n" +
	"\x13DeleteMovieTimeSlot\x12$.moviedb_service.MovieTimeSlotDelete\x1a&.moviedb_service.MovieTimeSlotResponseBFZDgithub.com/kartik7120/booking_moviedb_service/cmd/grpcServer;moviedbb\x06proto3"

var (
	file_moviedb_service_proto_rawDescOnce sync.Once
	file_moviedb_service_proto_rawDescData []byte
)

func file_moviedb_service_proto_rawDescGZIP() []byte {
	file_moviedb_service_proto_rawDescOnce.Do(func() {
		file_moviedb_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moviedb_service_proto_rawDesc), len(file_moviedb_service_proto_rawDesc)))
	})
	return file_moviedb_service_proto_rawDescData
}

var file_moviedb_service_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_moviedb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_moviedb_service_proto_goTypes = []any{
	(CastAndCrewType)(0),                // 0: moviedb_service.CastAndCrewType
	(VenueType)(0),                      // 1: moviedb_service.VenueType
	(SeatType)(0),                       // 2: moviedb_service.SeatType
	(SortBy)(0),                         // 3: moviedb_service.SortBy
	(FilterBy)(0),                       // 4: moviedb_service.FilterBy
	(*CastAndCrew)(nil),                 // 5: moviedb_service.CastAndCrew
	(*MovieTimeSlot)(nil),               // 6: moviedb_service.MovieTimeSlot
	(*Movie)(nil),                       // 7: moviedb_service.Movie
	(*SeatMatrix)(nil),                  // 8: moviedb_service.SeatMatrix
	(*Venue)(nil),                       // 9: moviedb_service.Venue
	(*MovieList)(nil),                   // 10: moviedb_service.MovieList
	(*MovieRequest)(nil),                // 11: moviedb_service.MovieRequest
	(*MovieResponse)(nil),               // 12: moviedb_service.MovieResponse
	(*MovieListResponse)(nil),           // 13: moviedb_service.MovieListResponse
	(*VenueResponse)(nil),               // 14: moviedb_service.VenueResponse
	(*GetUpcomingMovieRequest)(nil),     // 15: moviedb_service.GetUpcomingMovieRequest
	(*GetUpcomingMovieResponse)(nil),    // 16: moviedb_service.GetUpcomingMovieResponse
	(*GetNowPlayingMovieRequest)(nil),   // 17: moviedb_service.GetNowPlayingMovieRequest
	(*Review)(nil),                      // 18: moviedb_service.Review
	(*ReviewUpdateRequest)(nil),         // 19: moviedb_service.ReviewUpdateRequest
	(*ReviewResponse)(nil),              // 20: moviedb_service.ReviewResponse
	(*ReviewRequest)(nil),               // 21: moviedb_service.ReviewRequest
	(*ReviewList)(nil),                  // 22: moviedb_service.ReviewList
	(*ReviewListResponse)(nil),          // 23: moviedb_service.ReviewListResponse
	(*GetAllMovieReviewsRequest)(nil),   // 24: moviedb_service.GetAllMovieReviewsRequest
	(*GetMovieTimeSlotRequest)(nil),     // 25: moviedb_service.GetMovieTimeSlotRequest
	(*GetMovieTimeSlotResponse)(nil),    // 26: moviedb_service.GetMovieTimeSlotResponse
	(*MovieTimeSlotResponse)(nil),       // 27: moviedb_service.MovieTimeSlotResponse
	(*MovieTimeSlotUpdateResponse)(nil), // 28: moviedb_service.MovieTimeSlotUpdateResponse
	(*MovieTimeSlotUpdate)(nil),         // 29: moviedb_service.MovieTimeSlotUpdate
	(*MovieTimeSlotDelete)(nil),         // 30: moviedb_service.MovieTimeSlotDelete
	(*empty.Empty)(nil),                 // 31: google.protobuf.Empty
}
var file_moviedb_service_proto_depIdxs = []int32{
	0,  // 0: moviedb_service.CastAndCrew.type:type_name -> moviedb_service.CastAndCrewType
	2,  // 1: moviedb_service.MovieTimeSlot.movie_format:type_name -> moviedb_service.SeatType
	5,  // 2: moviedb_service.Movie.cast_crew:type_name -> moviedb_service.CastAndCrew
	9,  // 3: moviedb_service.Movie.venues:type_name -> moviedb_service.Venue
	2,  // 4: moviedb_service.SeatMatrix.type:type_name -> moviedb_service.SeatType
	1,  // 5: moviedb_service.Venue.type:type_name -> moviedb_service.VenueType
	8,  // 6: moviedb_service.Venue.seats:type_name -> moviedb_service.SeatMatrix
	6,  // 7: moviedb_service.Venue.movie_time_slots:type_name -> moviedb_service.MovieTimeSlot
	7,  // 8: moviedb_service.Venue.movies:type_name -> moviedb_service.Movie
	7,  // 9: moviedb_service.MovieList.movies:type_name -> moviedb_service.Movie
	7,  // 10: moviedb_service.MovieResponse.movie:type_name -> moviedb_service.Movie
	10, // 11: moviedb_service.MovieListResponse.movie_list:type_name -> moviedb_service.MovieList
	9,  // 12: moviedb_service.VenueResponse.Venue:type_name -> moviedb_service.Venue
	7,  // 13: moviedb_service.GetUpcomingMovieResponse.movie_list:type_name -> moviedb_service.Movie
	18, // 14: moviedb_service.ReviewResponse.review:type_name -> moviedb_service.Review
	18, // 15: moviedb_service.ReviewList.reviews:type_name -> moviedb_service.Review
	22, // 16: moviedb_service.ReviewListResponse.review_list:type_name -> moviedb_service.ReviewList
	3,  // 17: moviedb_service.GetAllMovieReviewsRequest.sortBy:type_name -> moviedb_service.SortBy
	4,  // 18: moviedb_service.GetAllMovieReviewsRequest.filterBy:type_name -> moviedb_service.FilterBy
	6,  // 19: moviedb_service.GetMovieTimeSlotResponse.movie_time_slots:type_name -> moviedb_service.MovieTimeSlot
	9,  // 20: moviedb_service.GetMovieTimeSlotResponse.venues:type_name -> moviedb_service.Venue
	6,  // 21: moviedb_service.MovieTimeSlotUpdateResponse.movie_time_slot:type_name -> moviedb_service.MovieTimeSlot
	2,  // 22: moviedb_service.MovieTimeSlotUpdate.movie_format:type_name -> moviedb_service.SeatType
	7,  // 23: moviedb_service.MovieDBService.AddMovie:input_type -> moviedb_service.Movie
	11, // 24: moviedb_service.MovieDBService.GetMovie:input_type -> moviedb_service.MovieRequest
	31, // 25: moviedb_service.MovieDBService.GetAllMovies:input_type -> google.protobuf.Empty
	7,  // 26: moviedb_service.MovieDBService.UpdateMovie:input_type -> moviedb_service.Movie
	11, // 27: moviedb_service.MovieDBService.DeleteMovie:input_type -> moviedb_service.MovieRequest
	9,  // 28: moviedb_service.MovieDBService.AddVenue:input_type -> moviedb_service.Venue
	11, // 29: moviedb_service.MovieDBService.GetVenue:input_type -> moviedb_service.MovieRequest
	31, // 30: moviedb_service.MovieDBService.GetAllVenues:input_type -> google.protobuf.Empty
	9,  // 31: moviedb_service.MovieDBService.UpdateVenue:input_type -> moviedb_service.Venue
	11, // 32: moviedb_service.MovieDBService.DeleteVenue:input_type -> moviedb_service.MovieRequest
	15, // 33: moviedb_service.MovieDBService.GetUpcomingMovies:input_type -> moviedb_service.GetUpcomingMovieRequest
	17, // 34: moviedb_service.MovieDBService.GetNowPlayingMovies:input_type -> moviedb_service.GetNowPlayingMovieRequest
	18, // 35: moviedb_service.MovieDBService.AddReview:input_type -> moviedb_service.Review
	21, // 36: moviedb_service.MovieDBService.GetReview:input_type -> moviedb_service.ReviewRequest
	19, // 37: moviedb_service.MovieDBService.UpdateReview:input_type -> moviedb_service.ReviewUpdateRequest
	21, // 38: moviedb_service.MovieDBService.DeleteReview:input_type -> moviedb_service.ReviewRequest
	24, // 39: moviedb_service.MovieDBService.GetAllMovieReviews:input_type -> moviedb_service.GetAllMovieReviewsRequest
	25, // 40: moviedb_service.MovieDBService.GetMovieTimeSlots:input_type -> moviedb_service.GetMovieTimeSlotRequest
	6,  // 41: moviedb_service.MovieDBService.AddMovieTimeSlot:input_type -> moviedb_service.MovieTimeSlot
	29, // 42: moviedb_service.MovieDBService.UpdateMovieTimeSlot:input_type -> moviedb_service.MovieTimeSlotUpdate
	30, // 43: moviedb_service.MovieDBService.DeleteMovieTimeSlot:input_type -> moviedb_service.MovieTimeSlotDelete
	12, // 44: moviedb_service.MovieDBService.AddMovie:output_type -> moviedb_service.MovieResponse
	12, // 45: moviedb_service.MovieDBService.GetMovie:output_type -> moviedb_service.MovieResponse
	13, // 46: moviedb_service.MovieDBService.GetAllMovies:output_type -> moviedb_service.MovieListResponse
	12, // 47: moviedb_service.MovieDBService.UpdateMovie:output_type -> moviedb_service.MovieResponse
	12, // 48: moviedb_service.MovieDBService.DeleteMovie:output_type -> moviedb_service.MovieResponse
	14, // 49: moviedb_service.MovieDBService.AddVenue:output_type -> moviedb_service.VenueResponse
	14, // 50: moviedb_service.MovieDBService.GetVenue:output_type -> moviedb_service.VenueResponse
	13, // 51: moviedb_service.MovieDBService.GetAllVenues:output_type -> moviedb_service.MovieListResponse
	14, // 52: moviedb_service.MovieDBService.UpdateVenue:output_type -> moviedb_service.VenueResponse
	12, // 53: moviedb_service.MovieDBService.DeleteVenue:output_type -> moviedb_service.MovieResponse
	16, // 54: moviedb_service.MovieDBService.GetUpcomingMovies:output_type -> moviedb_service.GetUpcomingMovieResponse
	16, // 55: moviedb_service.MovieDBService.GetNowPlayingMovies:output_type -> moviedb_service.GetUpcomingMovieResponse
	20, // 56: moviedb_service.MovieDBService.AddReview:output_type -> moviedb_service.ReviewResponse
	20, // 57: moviedb_service.MovieDBService.GetReview:output_type -> moviedb_service.ReviewResponse
	20, // 58: moviedb_service.MovieDBService.UpdateReview:output_type -> moviedb_service.ReviewResponse
	20, // 59: moviedb_service.MovieDBService.DeleteReview:output_type -> moviedb_service.ReviewResponse
	23, // 60: moviedb_service.MovieDBService.GetAllMovieReviews:output_type -> moviedb_service.ReviewListResponse
	26, // 61: moviedb_service.MovieDBService.GetMovieTimeSlots:output_type -> moviedb_service.GetMovieTimeSlotResponse
	27, // 62: moviedb_service.MovieDBService.AddMovieTimeSlot:output_type -> moviedb_service.MovieTimeSlotResponse
	28, // 63: moviedb_service.MovieDBService.UpdateMovieTimeSlot:output_type -> moviedb_service.MovieTimeSlotUpdateResponse
	27, // 64: moviedb_service.MovieDBService.DeleteMovieTimeSlot:output_type -> moviedb_service.MovieTimeSlotResponse
	44, // [44:65] is the sub-list for method output_type
	23, // [23:44] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_moviedb_service_proto_init() }
func file_moviedb_service_proto_init() {
	if File_moviedb_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moviedb_service_proto_rawDesc), len(file_moviedb_service_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moviedb_service_proto_goTypes,
		DependencyIndexes: file_moviedb_service_proto_depIdxs,
		EnumInfos:         file_moviedb_service_proto_enumTypes,
		MessageInfos:      file_moviedb_service_proto_msgTypes,
	}.Build()
	File_moviedb_service_proto = out.File
	file_moviedb_service_proto_goTypes = nil
	file_moviedb_service_proto_depIdxs = nil
}
